
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-04
owner: ucsb-cs156-s26
repo_name: team02-s26-04
pull_requests: [{"author":{"id":"U_kgDOBmaTag","is_bot":false,"login":"vanessaxu07","name":"Vanessa Xu"},"headRefName":"vanessa-UCSBDiningCommonsMenuItem-form","number":74,"title":"UCSBDiningCommonsMenuItem: Form and Tests Created","url":"https://github.com/ucsb-cs156-s26/team02-s26-04/pull/74"},{"author":{"id":"U_kgDOCeScdA","is_bot":false,"login":"GuaziBai","name":""},"headRefName":"annie-ucsborganization-table","number":73,"title":"Add UCSBOrganization table component","url":"https://github.com/ucsb-cs156-s26/team02-s26-04/pull/73"},{"author":{"id":"U_kgDOCM7v4A","is_bot":false,"login":"t-ladha","name":""},"headRefName":"tl-fixturesMenuItemReview","number":72,"title":"MenuItemReview fixtures added","url":"https://github.com/ucsb-cs156-s26/team02-s26-04/pull/72"},{"author":{"id":"U_kgDOCz-L6Q","is_bot":false,"login":"vincebnguyen","name":""},"headRefName":"articles-fixtures","number":71,"title":"Articles fixtures","url":"https://github.com/ucsb-cs156-s26/team02-s26-04/pull/71"},{"author":{"id":"U_kgDOCeRyWA","is_bot":false,"login":"Ertan10","name":"Ertan"},"headRefName":"Ertanteam02-1","number":70,"title":"crud operations","url":"https://github.com/ucsb-cs156-s26/team02-s26-04/pull/70"},{"author":{"id":"U_kgDOCeScdA","is_bot":false,"login":"GuaziBai","name":""},"headRefName":"annie-ucsborganization-form","number":69,"title":"Add UCSBOrganization form component","url":"https://github.com/ucsb-cs156-s26/team02-s26-04/pull/69"},{"author":{"id":"U_kgDOBuiegQ","is_bot":false,"login":"ErikRodriguez29","name":""},"headRefName":"39-create-fixtures-for-helprequest","number":68,"title":"Create fixtures for HelpRequest","url":"https://github.com/ucsb-cs156-s26/team02-s26-04/pull/68"}]
