
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-04
owner: ucsb-cs156-s26
repo_name: team02-s26-04
pull_requests: [{"author":{"id":"U_kgDOCz-L6Q","is_bot":false,"login":"vincebnguyen","name":""},"headRefName":"articles-create","number":105,"title":"Articles create","url":"https://github.com/ucsb-cs156-s26/team02-s26-04/pull/105"},{"author":{"id":"U_kgDOCz-L6Q","is_bot":false,"login":"vincebnguyen","name":""},"headRefName":"articles-placeholder","number":104,"title":"Articles placeholder","url":"https://github.com/ucsb-cs156-s26/team02-s26-04/pull/104"},{"author":{"id":"U_kgDOBuiegQ","is_bot":false,"login":"ErikRodriguez29","name":""},"headRefName":"45-edit-page-for-helprequest-plus-tests-and-stories","number":103,"title":"Edit page for HelpRequest plus tests and stories","url":"https://github.com/ucsb-cs156-s26/team02-s26-04/pull/103"},{"author":{"id":"U_kgDOCz-L6Q","is_bot":false,"login":"vincebnguyen","name":""},"headRefName":"articles-table","number":102,"title":"Articles table","url":"https://github.com/ucsb-cs156-s26/team02-s26-04/pull/102"},{"author":{"id":"U_kgDOBuiegQ","is_bot":false,"login":"ErikRodriguez29","name":""},"headRefName":"44-index-page-for-helprequest-plus-tests-and-stories","number":101,"title":"Index page for HelpRequest plus tests and stories","url":"https://github.com/ucsb-cs156-s26/team02-s26-04/pull/101"},{"author":{"id":"U_kgDOCM7v4A","is_bot":false,"login":"t-ladha","name":""},"headRefName":"tl-menuItemReviewEdit","number":100,"title":"MenuItemReview Edit page created","url":"https://github.com/ucsb-cs156-s26/team02-s26-04/pull/100"},{"author":{"id":"U_kgDOCM7v4A","is_bot":false,"login":"t-ladha","name":""},"headRefName":"tl-menuItemReviewIndex","number":99,"title":"MenuItemReview Index page created","url":"https://github.com/ucsb-cs156-s26/team02-s26-04/pull/99"},{"author":{"id":"U_kgDOCM7v4A","is_bot":false,"login":"t-ladha","name":""},"headRefName":"tl-menuItemReviewCreate","number":98,"title":"MenuItemReview Create Page ","url":"https://github.com/ucsb-cs156-s26/team02-s26-04/pull/98"}]
