
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-04
owner: ucsb-cs156-s26
repo_name: team02-s26-04
pull_requests: [{"author":{"id":"U_kgDOBmaTag","is_bot":false,"login":"vanessaxu07","name":"Vanessa Xu"},"headRefName":"vanessa-UCSBDiningCommonsMenuItem-fixtures","number":67,"title":"UCSBDiningCommonsMenuItem: Fixtures added","url":"https://github.com/ucsb-cs156-s26/team02-s26-04/pull/67"},{"author":{"id":"U_kgDOCM7v4A","is_bot":false,"login":"t-ladha","name":""},"headRefName":"tl-copyMenuItemReview","number":66,"title":"Copying MenuItemReview files from team01","url":"https://github.com/ucsb-cs156-s26/team02-s26-04/pull/66"},{"author":{"id":"U_kgDOCeScdA","is_bot":false,"login":"GuaziBai","name":""},"headRefName":"annie-ucsborganization-fixtures","number":65,"title":"Add UCSBOrganization fixtures","url":"https://github.com/ucsb-cs156-s26/team02-s26-04/pull/65"},{"author":{"id":"U_kgDOCz-L6Q","is_bot":false,"login":"vincebnguyen","name":""},"headRefName":"articles-team01","number":63,"title":"add code from articles-team01","url":"https://github.com/ucsb-cs156-s26/team02-s26-04/pull/63"}]
